[project]
name = 'stellar-protocol'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.edc-loan-contract]
path = 'contracts/edc-loan-contract.clar'
clarity_version = 2
epoch = 2.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
